---
displayWidth: 1280
displayHeight: 720
fullscreen: true
vsync: true
fpsLimit: 60
logLevel: "INFO"
loadMultiChunk: false
worlds:
  baseDir: "data/worlds"
controls:
  mouseSensitivity: 1.5
  invertMouseY: false
  keybinds:
    moveForward: "W"
    sprint: "LSHIFT"
    moveBackward: "S"
    moveRight: "D"
    moveLeft: "A"
    breakBlock: "MOUSE_LEFT"
    pause: "ESCAPE"
    placeBlock: "MOUSE_RIGHT"
graphics:
  windowMode: "FULLSCREEN"
  resolution: "1280x720"
  vsync: true
  fpsLimit: 60
  height: 720
  width: 1280
audio:
  masterVolume: 1.0
  musicVolume: 0.8
  effectsVolume: 0.8
  mute: false
